# Generated by Django 4.2.11 on 2024-05-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('username', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('url', django_cryptography.fields.encrypt(models.URLField(blank=True, max_length=255, null=True))),
                ('notes', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entries',
            },
        ),
    ]
